Adding basedpyright LSP

diff --git a/.config/bin/code_extensions b/.config/bin/code_extensions
--- a/.config/bin/code_extensions
+++ b/.config/bin/code_extensions
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 
 gum style \
-  --foreground 14 --border-foreground 14 --border double \
-  --margin "1 0" --padding "0 2" \
-  '
+    --foreground 14 --border-foreground 14 --border double \
+    --margin "1 0" --padding "0 2" \
+    '
 ██╗   ██╗███████╗ ██████╗ ██████╗ ██████╗ ███████╗
 ██║   ██║██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
 ██║   ██║███████╗██║     ██║   ██║██║  ██║█████╗
@@ -23,22 +23,22 @@ dotfiles_dir=$(pwd -P)
 extensios_dir=$dotfiles_dir/vscode/Library/Application\ Support/Code/User/extensions
 
 if [[ $# -eq 1 ]] || [[ $selected == "Exit" ]]; then
-  exit 1
+    exit 1
 fi
 
 if [[ $selected == "Save VSCode extensions" ]]; then
-  echo "Saving VSCode extensions..."
-  code --list-extensions > $extensions_dir
+    echo "Saving VSCode extensions..."
+    code --list-extensions > $extensions_dir
 fi
 
 if [[ $selected == "Install VSCode extensions" ]]; then
-  if [[ -f $extensios_dir ]]; then
-    echo "Installing VSCode extensions..."
-    extension_list=$(cat $extensios_dir)
-    for i in ${extension_list[@]}; do
-      code --install-extension $i
-    done
-  else
-    echo "VSCode extensions file not found."
-  fi
+    if [[ -f $extensios_dir ]]; then
+        echo "Installing VSCode extensions..."
+        extension_list=$(cat $extensios_dir)
+        for i in "${extension_list[@]}"; do
+            code --install-extension $i
+        done
+    else
+        echo "VSCode extensions file not found."
+    fi
 fi
